export const DumiData = {
    user: [
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",
            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",
            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",
            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",
            certificate: "",

            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/002",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/002",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: "",
            groupName: "",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,
            activityManagementNumber: "XXXXX\nXXXXX",

            serviceType: "시험",
            testNation: "대한민국",
            testCity: "서울",
            testDate: "24.01.10",
            testStartTime: "10:00",
            testEndTime: "16:00",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            isChoice: true,
            isShort: true,
            isLong: true,
            applicationStartDate: "24.01.10",
            applicationEndDate: "24.01.30",
            applicationStatus: "접수 전",
            examStatus: "시험 전",
            candidateStatus: "응시 전",
            announceDate: "24.10.10 월",
            announceTime: "10:00",
            examResults: true,
            scoredPoints: 80,
            feedbackStatus: "피드백 전",
            feedbackCompleteDate: "",

            certificate: "",
            paymentDate: "24.10.10",
            paymentDetails: "시험 응시",
            used: 100000,
            discount: -10000,
            discountDescription: "이벤트 할인",
            paymentAmount: 90000,
            paymentMethod: "카드 결제",
            availablePoints: 12000,
            refundStatus: "",

            consultationDate: "24.01.10",
            consultationCompleteDate: "24.01.30",
            consultationStatus: "문의 요청",
            inquiryCategory: "결제",
            answerCategory: "관리자",
            answerer: "김관리",
            inquiryTitle: "제목이 ...",
            inquiryContents: "글자5개마우스오버시 모두...",
            attachedFile: "",
            adminMemo: "입력한 텍스트 ..."

        }],
    expert: [
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
        {
            id: "UI240110/001",
            site: "메타번역",
            userType: "정식 회원",
            userSubscriptionStatus: "프리미엄 구독",
            name: "홍길동",
            age: 34,
            gender: "남",
            email: "abce@gmail.com",
            mobilePhone: "+82 1012345678",
            city: "서울",
            address: "강남구",
            groupStatus: true,
            groupName: "삼성",
            joinDate: "24.10.30",
            joinChannel: "카카오",
            firstAccessDevice: "모바일",
            recentLogin: "24.10.10 월",
            stayTime: "1h15m 30s",
            photo: "image.gif",
            alertKaKao: true,
            alertSms: true,
            alertEmail: true,
            marketingKaKao: true,
            marketingSms: true,
            marketingEmail: true,

            resume: "이력서",
            categoryB: "카테고리(대)",
            categoryM: "카테고리(중)",
            categoryS: "카테고리(소)",
            expertServiceType: "시험 출제",
            serviceTime: "언제든지",
            expertStatus: "전문가 승인",
            expertDate: "24.10.10",
            priority: 1,
            expertLevel: "A",
            rating: 4.5,
            reviews: 10,
            activities: 44,
            matchingDecline: 10,
            settleBank: "은행명",
            settleAccount: "XXXXX...",
            settleOwner: "예금주",
            totalCareer: "20년 12개월",
            education: "예일대",

            testNation: "대한민국",
            testCity: "서울",
            applicationCategory: "정시",
            year: 25,
            round: 1,
            testSubject: "번역 전문가",
            testGrade: "전문1급",
            category1: "카테고리(대)",
            category2: "카테고리(중)",
            category3: "카테고리(소)",
            examName: "시험명 표시 영역",
            detailedDescription: "(세부명)",
            departureLanguage: "한국어",
            arrivalLanguage: "English(US)",
            purpose: "응시용",
            activityCareer: "시험 출제",
            activityCareerCount: "1",
            activityDoneDate: "24.01.10",
            settleDueDate: "24.01.30",
            settlePlaned: 100000,
            settleAddition: -10000,
            settleAmount: 90000,
            settleStatus: "정산 완료",
            settledDate: "24.01.10",
            unspent: 90000,
            adminMemo: "입력한 텍스트 ..."

        },
    ],
    test: [
        {
            id:"UI240110<br/>005",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>006",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
        {
            id:"UI240110<br/>007",
            siteCategory:"집단지성<br/>큐레이터",
            testAvailableStartDate:"YY.MM.DD",
            testAvailableEndDate:"YY.MM.DD",
            testNation:"대한민국",
            testCity:"서울",
            testDate:"YY.MM.DD.DOW",
            testStartTime:"14:00",
            testEndTime:"14:30",
            applicationCategory:"정시",
            year:"24",
            round:"10",
            testSubject:"AITe 번역 전문가",
            testGrade:"전문1급",
            category1:"카테고리(대)",
            category2:"카테고리(중)",
            category3:"카테고리(소)",
            examName:"시험명 표시 영역",
            detailedDescription:"",
            departureLanguage:"한국어",
            arrivalLanguage:"English(US)",
            purpose:"응시용",
            defaultValue:"기본값",
            order:"2교시",
            submittingStartDate:"YY.MM.DD",
            submittingEndDate:"YY.MM.DD",
            submittingStatus:"출제중",
            questionFile:"filename.docx",
            fileType:"음성",
            translationToolUsed:"DeepL<br/>파파고",
            aiUsed:"ChatGPT<br/>Bing",
            testOverview:"입력한 텍스트 ...",
            passingScore:60,
            fullScore:100,
            searchCount:30,
            totalNumberOfQuestions:"24",
            levelHigh:"11",
            levelMedium:"10",
            levelLow:"3",
            questionSetter:"김출제",
            questionSetterContact:"01012345678",
            applicationStartDate:"YY.MM.DD",
            applicationEndDate:"YY.MM.DD",
            applicationStatus:"접수 완료",
            testingStatus:"시험 중",
            gradingStartDate:"YY.MM.DD",
            gradingEndDate:"YY.MM.DD",
            gradingStatus:"체점 전",
            grader:"김출제",
            graderContact:"01012345678",
            announceDate:"YY.MM.DD. DOW",
            announceTime:"10:00",
            numberOfApplicants:"100",
            previousNumberOfApplicants:"50",
            passers:"90",
            failers:"10",
            questionSetterMemo:"입력한 텍스트 ...",
            graderMemo:"입력한 텍스트 ...",
            adminMemo:"입력한 텍스트 ...",
        },
    ],
    grading: [],
    blog: [],
    support: [],
    site: [],
    category: [],
    transaction: [],
    admin: [],
}